### PR TITLE
Resolve VCSWP-19763 (Add autogenerated unit tests for NodeJS SDK)

### PR DESCRIPTION
**Pull request by amahadaya**
Closes VCSWP-19763

### CODE REVIEW

**Review by edgeston — CHANGES_REQUESTED** [review]
@amahadaya - PR looks good to me.
Just want to clarify a couple of things

- Is deserialization not needed in this SDK? 
- I remember you said no method testing was needed prior to you working on this? Why is that?

**Comment by amahadaya** [comment]
> @amahadaya - PR looks good to me. Just want to clarify a couple of things
> 
> * Is deserialization not needed in this SDK?
> * I remember you said no method testing was needed prior to you working on this? Why is that?

- deserialization is not needed because the enums are already connected to strings
- there aren't any functions/methods that I saw in any of the model classes that I seen so far which is why I don't have method tests

**Review by edgeston — APPROVED** [review]
This looks good to me. Approved!

**Review by lunderwood99 — APPROVED** [review]
+1

**Review by jbohnevail — APPROVED** [review]
Looks good to me, +1

**Pull request merged**
